# Project information
site_name: My MkDocs Project
site_description: 'An example MkDocs project using the Material theme'
site_url: https://tegha-romeo.github.io/mk-docs  # Change this to your site's URL

# Theme settings
theme:
  name: material

# Navbar settings (site structure)
nav:
  - Home: index.md
  - About: about.md
  - Sample: sample.md
  - multipass: multipass.md
# Extra settings
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

# Repository configuration (for the edit link on pages)
repo_name: ADORSYS-GIS/mk-docs
repo_url: https://github.com/tegha-romeo/mk-docs
edit_uri: edit/main/docs/
